name: Create ALF File

on: 
  watch:
    types: [started]
  
jobs:
  build-linux: 
    if: 1 == 0
    runs-on: ubuntu-20.04
    steps:
    - run: |
        mkdir ~/git
        cd ~/git
        git clone https://github.com/NationalSecurityAgency/ghidra.git
        cd ~/git/ghidra
        gradle --init-script gradle/support/fetchDependencies.gradle init
    - run: |
        cd ~/git/ghidra
        gradle buildGhidra
    - uses: actions/upload-artifact@master
      with:
        path: ~/git/ghidra/build/dist/
        name: GhidraBuild
  build-win:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    strategy:
      matrix:
        unity-tag:
          - 2020.1.7f1-linux-il2cpp
          - 2019.4.11f1-linux-il2cpp
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.300' # SDK
    - run: |
        export PATH="$PATH:/github/home/.dotnet/tools"
        dotnet tool install ilspycmd -g
    - run: ls /opt/Unity/Editor/Data/il2cpp/build
    - run: |
        mkdir outputFolder
        ilspycmd "/opt/Unity/Editor/Data/il2cpp/build/il2cpp" -o outputFolder -p
    - run: ls outputFolder
