name: Create ALF File

on: 
  schedule:
  - cron:  '53 * * * *'
  
jobs:
  build: 
    runs-on: ubuntu-20.04
    steps:
    - run: |
        mkdir ~/git
        cd ~/git
        git clone https://github.com/NationalSecurityAgency/ghidra.git
    - run: 
        ls
        cd ~/git
        ls
    - run: |
        cd ~/git
        gradle --init-script gradle/support/fetchDependencies.gradle init
        gradle buildGhidra

    - uses: actions/upload-artifact@master
      with:
        path: ~/git/ghidra/build/dist/
        name: GhidraBuild
