name: Create ALF File

on: 
  watch:
    types: [started]
  
jobs:
  build-linux: 
    if: 1 == 0
    runs-on: ubuntu-20.04
    steps:
    - run: |
        mkdir ~/git
        cd ~/git
        git clone https://github.com/NationalSecurityAgency/ghidra.git
        cd ~/git/ghidra
        gradle --init-script gradle/support/fetchDependencies.gradle init
    - run: |
        cd ~/git/ghidra
        gradle buildGhidra
    - uses: actions/upload-artifact@master
      with:
        path: ~/git/ghidra/build/dist/
        name: GhidraBuild
  build-win:
    runs-on: windows-latest
    steps:
    - run: |
        curl -OL https://jaist.dl.sourceforge.net/project/gnuwin32/bison/2.4.1/bison-2.4.1-setup.exe
        dir
    - run: |
        curl -OL https://jaist.dl.sourceforge.net/project/gnuwin32/flex/2.5.4a-1/flex-2.5.4a-1.exe
        dir
    - run: ./bison-2.4.1-setup.exe
    - run: ./flex-2.5.4a-1.exe
    - run: dir
    - run: |
        cd "C:\"
        dir
