name: Create ALF File

on: 
  watch:
    types: [started]
  
jobs:
  build: 
    runs-on: ubuntu-20.04
    steps:
    - run: |
        mkdir ~/git
        cd ~/git
        git clone https://github.com/NationalSecurityAgency/ghidra.git
        cd ~/git/ghidra
        gradle --init-script gradle/support/fetchDependencies.gradle init
    - run: echo -e -n "\\napplication.allPlatforms=" >> ~/git/ghidra/Ghidra/application.properties
    - run: |
        cd ~/git/ghidra
        gradle buildGhidra

    - uses: actions/upload-artifact@master
      with:
        path: ~/git/ghidra/build/dist/
        name: GhidraBuild
